const common = {
  en: { save:'Save', update:'Update', add:'Add', edit:'Edit', delete:'Delete', cancel:'Cancel', close:'Close', loading:'Loading…', search:'Search', notes:'Notes', date:'Date', time:'Time', optional:'Optional', required:'Required', view:'View', call:'Call', comments:'Comments', noData:'No records found.', yes:'Yes', no:'No' },
  si: { save:'සුරකින්න', update:'යාවත්කාලීන කරන්න', add:'එක් කරන්න', edit:'සංස්කරණය', delete:'මකන්න', cancel:'අවලංගු කරන්න', close:'වසන්න', loading:'පූරණය වෙමින්…', search:'සොයන්න', notes:'සටහන්', date:'දිනය', time:'වේලාව', optional:'විකල්ප', required:'අවශ්‍යයි', view:'බලන්න', call:'අමතන්න', comments:'අදහස්', noData:'වාර්තා හමු නොවීය.', yes:'ඔව්', no:'නැහැ' },
  ta: { save:'சேமிக்கவும்', update:'புதுப்பிக்கவும்', add:'சேர்க்கவும்', edit:'திருத்தவும்', delete:'நீக்கவும்', cancel:'ரத்து செய்க', close:'மூடவும்', loading:'ஏற்றுகிறது…', search:'தேடவும்', notes:'குறிப்புகள்', date:'தேதி', time:'நேரம்', optional:'விருப்பம்', required:'தேவை', view:'பார்க்க', call:'அழைக்க', comments:'கருத்துகள்', noData:'பதிவுகள் இல்லை.', yes:'ஆம்', no:'இல்லை' }
};

export const translations = {
  en: {
    ...common.en, appName:'MomCare LK', tagline:"Sri Lanka's all-in-one platform for pregnant mothers",
    nav:{home:'Home',tracker:'Tracker',appointments:'Appointments',careTeam:'Care Team',health:'Health Records',emergency:'Emergency',shopping:'Nearby Finder',wellbeing:'Wellbeing'},
    auth:{login:'Log In',register:'Sign Up',logout:'Log Out',email:'Email',password:'Password',fullName:'Full name',accountType:'Account type',noAccount:"Don't have an account?",haveAccount:'Already have an account?',loginWelcome:'Welcome back! Log in to continue.',registerWelcome:'Create your MomCare account.',demoAccounts:'Demo accounts',familyCode:'Family invitation code',familyHelp:'Ask the mother for her private family code.'},
    roles:{mom:'Mother',partner:'Partner',doctor:'Doctor / Midwife',momAccess:'Mother access',partnerAccess:'Partner access',doctorAccess:'Doctor / Midwife access',readOnly:'Read-only access',readOnlyText:"You can view the mother's shared information, but you cannot change it."},
    home:{welcome:'Welcome back',week:'Week',of40:'of 40',dueDate:'Due date',babyThisWeek:'Your baby this week',nextAppointment:'Next clinic appointment',viewAppointments:'View appointments →',trackerTitle:'Pregnancy Tracker',trackerDesc:'Follow your pregnancy week by week.',appointmentsTitle:'Clinic Appointments',appointmentsDesc:'Plan clinic visits and keep reminders together.',careTitle:'Care Team & Access',careDesc:'View linked accounts, permissions, and care comments.'},
    pregnancy:{journey:'Your pregnancy journey',estimatedDue:'Estimated due date',ownerNotice:'Pregnancy dates belong to the mother. You may review the tracker and add a comment from the Care Team page.',setDates:'Set pregnancy dates',lmp:'Last menstrual period date',update:'Update tracker',updated:'Pregnancy dates updated successfully.',development:'Baby development',motherChanges:'Changes for mother',clinicGuidance:'Clinic guidance',explore:'Explore all 40 weeks',size:'Size',disclaimer:'This tracker provides general educational information. Confirm pregnancy dates and care plans with a qualified healthcare professional.'},
    appointments:{title:'Clinic appointments',readonly:'Appointments are read-only for your role. Only the mother can add, edit, complete, or delete them. You can add a care comment instead.',addTitle:'Add clinic appointment',editTitle:'Edit clinic appointment',hospital:'Hospital / clinic',hospitalPh:'e.g. MOH Office Nugegoda',doctor:'Doctor / midwife',type:'Appointment type',routine:'Routine antenatal clinic',scan:'Ultrasound scan',blood:'Blood test',vaccination:'Vaccination',specialist:'Specialist consultation',other:'Other',notesPh:'Clinic book, reports, questions to ask…',reminder:'Enable in-app reminder',saveChanges:'Save changes',addAppointment:'Add appointment',next:'Next appointment',reminderEnabled:'Reminder enabled. This app displays reminders inside MomCare.',myAppointments:'My appointments',empty:'No appointments added yet.',added:'Appointment added.',updated:'Appointment updated.',deleteConfirm:'Delete this appointment?'},
    health:{title:'Digital Health Records',desc:'Store blood pressure, weight, and scan reports in one protected family record.',readonly:'These records are read-only for your role. You may review them and add a comment, but only the mother can create, edit, replace, or delete records.',addTitle:'Add health record',editTitle:'Edit health record',recordType:'Record type',weight:'Weight',bloodPressure:'Blood pressure',scanReport:'Scan report',weightKg:'Weight (kg)',systolic:'Systolic',diastolic:'Diastolic',pulse:'Pulse',reportTitle:'Report title',scanType:'Scan type',file:'Report file',all:'All records',open:'Open report',deleteConfirm:'Delete this health record permanently?',openError:'Unable to open scan report'},
    emergency:{title:'One-touch SOS',desc:'Use this only when urgent help is needed. Your current location will be prepared for sharing with saved emergency contacts.',button:'Send Emergency SOS',locating:'LOCATING…',needContact:'The mother must save at least one emergency contact first.',contacts:'Pre-saved emergency contacts',name:'Contact name',relationship:'Relationship (Partner, Sister…)',phone:'Phone number',priority:'Priority',saveContact:'Save contact',updateContact:'Update contact',sms:'SMS',call:'Call',openMaps:'Open captured location in Maps',history:'Latest SOS actions',notSupported:'Location is not supported by this browser.',denied:'Location permission was denied.',failed:'Your location could not be captured.',requesting:'Requesting your current location…'},
    finder:{title:'Nearby Hospitals, Pharmacies & Baby Shops',desc:'Use device GPS or enter coordinates manually. For local development, browser GPS normally works only on localhost or HTTPS.',useLocation:'Use my location',colombo:'Use Colombo demo',latitude:'Latitude, e.g. 6.9271',longitude:'Longitude, e.g. 79.8612',searchHere:'Search here',all:'All places',hospitals:'Hospitals',pharmacies:'Pharmacies',shops:'Baby shops',within:'Within {km} km',centre:'Search centre',openHospitals:'Open hospitals in Google Maps',openShops:'Open baby shops in Google Maps',results:'Nearby results',filter:'Filter by name or area',start:'Choose your location above to begin searching.',noResults:'No mapped places were found in this radius. Try a larger radius or Google Maps.',directions:'Directions',mapNote:'Place results are provided by Google Places when configured, with OpenStreetMap as a backup. Always call ahead to confirm services and opening hours.',source:'Data source',selected:'Selected',openNow:'Open now',closedNow:'Closed now',addressUnavailable:'Address unavailable',gpsHttps:'Browser location needs HTTPS or localhost. Use the manual location option below.',invalid:'Enter valid latitude and longitude values.'},
    care:{signedIn:'Signed in with',linked:'Linked care team',invitation:'Family invitation code',inviteHelp:'Share this code only with your trusted partner or healthcare professional.',permissions:'Permission summary',area:'Area',viewEdit:'View & edit',viewOnly:'View only',addEditDelete:'Add, edit & delete',careComments:'Care team comments',pregnancyDates:'Pregnancy dates',appointments:'Appointments',healthRecords:'Health records',addComment:'Add comment',commentAdded:'Comment added successfully.'},
    wellbeing:{mood:'How are you feeling today?',thanks:'Thank you for checking in. Your wellbeing matters!',forum:'Community Forum',placeholder:'Share a question or experience…',post:'Post'},
    footer:'MomCare LK — CCS2313 Mini Project Demo · Group 05'
  },
  si: {
    ...common.si, appName:'MomCare LK', tagline:'ගැබිනි මව්වරුන් සඳහා ශ්‍රී ලංකාවේ සර්ව සම්පූර්ණ වේදිකාව', demoBadge:'ආදර්ශ අනුවාදය',
    nav:{home:'මුල් පිටුව',tracker:'ගර්භණී ට්‍රැකර්',appointments:'සායන හමුවීම්',careTeam:'සත්කාර කණ්ඩායම',health:'සෞඛ්‍ය වාර්තා',emergency:'හදිසි SOS',shopping:'ආසන්න ස්ථාන',wellbeing:'මානසික සුවය'},
    auth:{login:'පිවිසෙන්න',register:'ලියාපදිංචි වන්න',logout:'ඉවත් වන්න',email:'විද්‍යුත් තැපෑල',password:'මුරපදය',fullName:'සම්පූර්ණ නම',accountType:'ගිණුම් වර්ගය',noAccount:'ගිණුමක් නැද්ද?',haveAccount:'දැනටමත් ගිණුමක් තිබේද?',loginWelcome:'නැවත සාදරයෙන් පිළිගනිමු! ඉදිරියට යාමට පිවිසෙන්න.',registerWelcome:'ඔබේ MomCare ගිණුම සාදන්න.',demoAccounts:'ආදර්ශ ගිණුම්',familyCode:'පවුල් ආරාධනා කේතය',familyHelp:'මවගෙන් පෞද්ගලික පවුල් කේතය ලබාගන්න.'},
    roles:{mom:'මව',partner:'සහකරු',doctor:'වෛද්‍ය / වින්නඹු මාතාව',momAccess:'මවගේ ප්‍රවේශය',partnerAccess:'සහකරුගේ ප්‍රවේශය',doctorAccess:'වෛද්‍ය / වින්නඹු ප්‍රවේශය',readOnly:'බැලීමට පමණයි',readOnlyText:'මව බෙදාගත් තොරතුරු බැලිය හැකි නමුත් වෙනස් කළ නොහැක.'},
    home:{welcome:'නැවත සාදරයෙන් පිළිගනිමු',week:'සතිය',of40:'40 න්',dueDate:'ඇස්තමේන්තුගත ප්‍රසව දිනය',babyThisWeek:'මෙම සතියේ ඔබේ බිළිඳා',nextAppointment:'මීළඟ සායන හමුවීම',viewAppointments:'හමුවීම් බලන්න →',trackerTitle:'ගර්භණී ට්‍රැකර්',trackerDesc:'සතියෙන් සතිය ගර්භණී ගමන අනුගමනය කරන්න.',appointmentsTitle:'සායන හමුවීම්',appointmentsDesc:'සායන සංචාර සහ මතක් කිරීම් සැලසුම් කරන්න.',careTitle:'සත්කාර කණ්ඩායම සහ ප්‍රවේශය',careDesc:'සම්බන්ධිත ගිණුම්, අවසර සහ අදහස් බලන්න.'},
    pregnancy:{journey:'ඔබේ ගර්භණී ගමන',estimatedDue:'ඇස්තමේන්තුගත ප්‍රසව දිනය',ownerNotice:'ගර්භණී දින මවට අයත් වේ. ඔබට ට්‍රැකර් එක බැලීමට සහ සත්කාර කණ්ඩායම් පිටුවෙන් අදහසක් එක් කිරීමට හැක.',setDates:'ගර්භණී දින සකසන්න',lmp:'අවසන් මාසික වාරයේ දිනය',update:'ට්‍රැකර් යාවත්කාලීන කරන්න',updated:'ගර්භණී දින සාර්ථකව යාවත්කාලීන කරන ලදී.',development:'බිළිඳාගේ වර්ධනය',motherChanges:'මවගේ වෙනස්කම්',clinicGuidance:'සායන මාර්ගෝපදේශ',explore:'සති 40ම බලන්න',size:'ප්‍රමාණය',disclaimer:'මෙය සාමාන්‍ය අධ්‍යාපනික තොරතුරු සපයයි. සුදුසු සෞඛ්‍ය වෘත්තිකයෙකු සමඟ දින සහ සත්කාර සැලැස්ම තහවුරු කරන්න.'},
    appointments:{title:'සායන හමුවීම්',readonly:'ඔබේ භූමිකාවට හමුවීම් බැලීමට පමණයි. එක් කිරීම, සංස්කරණය හෝ මකා දැමීම කළ හැක්කේ මවට පමණි.',addTitle:'සායන හමුවීමක් එක් කරන්න',editTitle:'සායන හමුවීම සංස්කරණය',hospital:'රෝහල / සායනය',hospitalPh:'උදා: නුගේගොඩ MOH කාර්යාලය',doctor:'වෛද්‍ය / වින්නඹු මාතාව',type:'හමුවීම් වර්ගය',routine:'සාමාන්‍ය ගර්භණී සායනය',scan:'අල්ට්‍රා සවුන්ඩ් ස්කෑන්',blood:'රුධිර පරීක්ෂණය',vaccination:'එන්නත',specialist:'විශේෂඥ හමුවීම',other:'වෙනත්',notesPh:'සායන පොත, වාර්තා, අසන්න ප්‍රශ්න…',reminder:'යෙදුම තුළ මතක් කිරීම සක්‍රීය කරන්න',saveChanges:'වෙනස්කම් සුරකින්න',addAppointment:'හමුවීම එක් කරන්න',next:'මීළඟ හමුවීම',reminderEnabled:'මතක් කිරීම සක්‍රීයයි.',myAppointments:'මගේ හමුවීම්',empty:'හමුවීම් තවම එක් කර නැත.',added:'හමුවීම එක් කරන ලදී.',updated:'හමුවීම යාවත්කාලීන කරන ලදී.',deleteConfirm:'මෙම හමුවීම මකන්නද?'},
    health:{title:'ඩිජිටල් සෞඛ්‍ය වාර්තා',desc:'රුධිර පීඩනය, බර සහ ස්කෑන් වාර්තා ආරක්ෂිතව තබාගන්න.',readonly:'ඔබේ භූමිකාවට වාර්තා බැලීමට සහ අදහස් එක් කිරීමට හැක. වාර්තා එක් කිරීම, වෙනස් කිරීම හෝ මකා දැමීම කළ හැක්කේ මවට පමණි.',addTitle:'සෞඛ්‍ය වාර්තාවක් එක් කරන්න',editTitle:'සෞඛ්‍ය වාර්තාව සංස්කරණය',recordType:'වාර්තා වර්ගය',weight:'බර',bloodPressure:'රුධිර පීඩනය',scanReport:'ස්කෑන් වාර්තාව',weightKg:'බර (kg)',systolic:'සිස්ටොලික්',diastolic:'ඩයස්ටොලික්',pulse:'නාඩි වේගය',reportTitle:'වාර්තා මාතෘකාව',scanType:'ස්කෑන් වර්ගය',file:'වාර්තා ගොනුව',all:'සියලු වාර්තා',open:'වාර්තාව විවෘත කරන්න',deleteConfirm:'මෙම සෞඛ්‍ය වාර්තාව ස්ථිරව මකන්නද?',openError:'ස්කෑන් වාර්තාව විවෘත කළ නොහැක'},
    emergency:{title:'එක්-ස්පර්ශ SOS',desc:'හදිසි උපකාර අවශ්‍ය විට පමණක් භාවිත කරන්න. ඔබේ වත්මන් ස්ථානය සුරකින ලද සම්බන්ධතා වෙත බෙදාගැනීමට සූදානම් කරයි.',button:'හදිසි SOS යවන්න',locating:'ස්ථානය සොයමින්…',needContact:'පළමුව මව අවම වශයෙන් එක් හදිසි සම්බන්ධතාවක් සුරැකිය යුතුය.',contacts:'සුරකින ලද හදිසි සම්බන්ධතා',name:'සම්බන්ධතා නම',relationship:'සම්බන්ධතාවය (සහකරු, සහෝදරිය…)',phone:'දුරකථන අංකය',priority:'ප්‍රමුඛතාව',saveContact:'සම්බන්ධතාව සුරකින්න',updateContact:'සම්බන්ධතාව යාවත්කාලීන කරන්න',sms:'SMS',call:'අමතන්න',openMaps:'සිතියමේ ස්ථානය විවෘත කරන්න',history:'නවතම SOS ක්‍රියා',notSupported:'මෙම බ්‍රවුසරය ස්ථානය සඳහා සහය නොදක්වයි.',denied:'ස්ථාන අවසරය ප්‍රතික්ෂේප විය.',failed:'ඔබේ ස්ථානය ලබාගත නොහැකි විය.',requesting:'ඔබේ වත්මන් ස්ථානය ලබාගනිමින්…'},
    finder:{title:'ආසන්න රෝහල්, ඖෂධසැල් සහ ළදරු සාප්පු',desc:'උපාංග GPS භාවිත කරන්න හෝ ඛණ්ඩාංක ඇතුළත් කරන්න. දේශීය සංවර්ධනයේදී GPS සාමාන්‍යයෙන් localhost හෝ HTTPS මත පමණක් ක්‍රියා කරයි.',useLocation:'මගේ ස්ථානය භාවිත කරන්න',colombo:'කොළඹ ආදර්ශය භාවිත කරන්න',latitude:'අක්ෂාංශය, උදා: 6.9271',longitude:'දේශාංශය, උදා: 79.8612',searchHere:'මෙහි සොයන්න',all:'සියලු ස්ථාන',hospitals:'රෝහල්',pharmacies:'ඖෂධසැල්',shops:'ළදරු සාප්පු',within:'කි.මී. {km} තුළ',centre:'සෙවුම් මධ්‍යස්ථානය',openHospitals:'Google Maps හි රෝහල් විවෘත කරන්න',openShops:'Google Maps හි ළදරු සාප්පු විවෘත කරන්න',results:'ආසන්න ප්‍රතිඵල',filter:'නම හෝ ප්‍රදේශය අනුව පෙරහන් කරන්න',start:'සෙවීම ආරම්භ කිරීමට ඉහළින් ස්ථානය තෝරන්න.',noResults:'මෙම දුර තුළ සිතියම්ගත ස්ථාන හමු නොවීය. වැඩි දුරක් හෝ Google Maps භාවිත කරන්න.',directions:'මාර්ග උපදෙස්',mapNote:'Google Places සකසා ඇති විට එහි ස්ථාන දත්ත භාවිත වේ; OpenStreetMap උපස්ථයක් ලෙස භාවිත වේ. සේවා සහ විවෘත වේලාවන් කලින් තහවුරු කරන්න.',source:'දත්ත මූලාශ්‍රය',selected:'තෝරාගත්',openNow:'දැන් විවෘතයි',closedNow:'දැන් වසා ඇත',addressUnavailable:'ලිපිනය නොමැත',gpsHttps:'බ්‍රවුසර ස්ථානය සඳහා HTTPS හෝ localhost අවශ්‍යයි. අතින් ස්ථානය ඇතුළත් කරන්න.',invalid:'වලංගු අක්ෂාංශ හා දේශාංශ අගයන් ඇතුළත් කරන්න.'},
    care:{signedIn:'පිවිසී ඇත්තේ',linked:'සම්බන්ධිත සත්කාර කණ්ඩායම',invitation:'පවුල් ආරාධනා කේතය',inviteHelp:'මෙම කේතය විශ්වාසවන්ත සහකරු හෝ සෞඛ්‍ය වෘත්තිකයෙකු සමඟ පමණක් බෙදාගන්න.',permissions:'අවසර සාරාංශය',area:'අංශය',viewEdit:'බලන්න සහ වෙනස් කරන්න',viewOnly:'බැලීමට පමණයි',addEditDelete:'එක් කරන්න, වෙනස් කරන්න සහ මකන්න',careComments:'සත්කාර කණ්ඩායම් අදහස්',pregnancyDates:'ගර්භණී දින',appointments:'හමුවීම්',healthRecords:'සෞඛ්‍ය වාර්තා',addComment:'අදහස එක් කරන්න',commentAdded:'අදහස සාර්ථකව එක් කරන ලදී.'},
    wellbeing:{mood:'අද ඔබට කෙසේද?',thanks:'පිළිතුරු දුන්නාට ස්තූතියි. ඔබේ සුවය වැදගත්!',forum:'ප්‍රජා සංසදය',placeholder:'ප්‍රශ්නයක් හෝ අත්දැකීමක් බෙදාගන්න…',post:'පළ කරන්න'},
    footer:'MomCare LK — CCS2313 කුඩා ව්‍යාපෘති ආදර්ශය · කණ්ඩායම 05'
  },
  ta: {
    ...common.ta, appName:'MomCare LK', tagline:'கர்ப்பிணித் தாய்மார்களுக்கான இலங்கையின் முழுமையான தளம்', demoBadge:'மாதிரி பதிப்பு',
    nav:{home:'முகப்பு',tracker:'கர்ப்ப கண்காணிப்பு',appointments:'கிளினிக் சந்திப்புகள்',careTeam:'பராமரிப்பு குழு',health:'சுகாதார பதிவுகள்',emergency:'அவசர SOS',shopping:'அருகிலுள்ள இடங்கள்',wellbeing:'நல்வாழ்வு'},
    auth:{login:'உள்நுழைக',register:'பதிவு செய்க',logout:'வெளியேறு',email:'மின்னஞ்சல்',password:'கடவுச்சொல்',fullName:'முழு பெயர்',accountType:'கணக்கு வகை',noAccount:'கணக்கு இல்லையா?',haveAccount:'ஏற்கனவே கணக்கு உள்ளதா?',loginWelcome:'மீண்டும் வரவேற்கிறோம்! தொடர உள்நுழையவும்.',registerWelcome:'உங்கள் MomCare கணக்கை உருவாக்கவும்.',demoAccounts:'மாதிரி கணக்குகள்',familyCode:'குடும்ப அழைப்புக் குறியீடு',familyHelp:'தாயிடமிருந்து தனிப்பட்ட குடும்பக் குறியீட்டை பெறவும்.'},
    roles:{mom:'தாய்',partner:'துணைவர்',doctor:'மருத்துவர் / மருத்துவச்சி',momAccess:'தாய் அணுகல்',partnerAccess:'துணைவர் அணுகல்',doctorAccess:'மருத்துவர் / மருத்துவச்சி அணுகல்',readOnly:'பார்வை மட்டும்',readOnlyText:'தாய் பகிர்ந்த தகவல்களை பார்க்கலாம்; மாற்ற முடியாது.'},
    home:{welcome:'மீண்டும் வரவேற்கிறோம்',week:'வாரம்',of40:'40 இல்',dueDate:'எதிர்பார்க்கப்படும் பிரசவ தேதி',babyThisWeek:'இந்த வாரம் உங்கள் குழந்தை',nextAppointment:'அடுத்த கிளினிக் சந்திப்பு',viewAppointments:'சந்திப்புகளை பார்க்க →',trackerTitle:'கர்ப்ப கண்காணிப்பு',trackerDesc:'வாரம் வாரமாக உங்கள் கர்ப்ப பயணத்தை பின்தொடருங்கள்.',appointmentsTitle:'கிளினிக் சந்திப்புகள்',appointmentsDesc:'கிளினிக் வருகைகளையும் நினைவூட்டல்களையும் திட்டமிடுங்கள்.',careTitle:'பராமரிப்பு குழு மற்றும் அணுகல்',careDesc:'இணைக்கப்பட்ட கணக்குகள், அனுமதிகள் மற்றும் கருத்துகளை பார்க்கவும்.'},
    pregnancy:{journey:'உங்கள் கர்ப்ப பயணம்',estimatedDue:'எதிர்பார்க்கப்படும் பிரசவ தேதி',ownerNotice:'கர்ப்ப தேதிகள் தாய்க்குச் சொந்தமானவை. கண்காணிப்பை பார்க்கவும் பராமரிப்பு குழு பக்கத்தில் கருத்து சேர்க்கவும் முடியும்.',setDates:'கர்ப்ப தேதிகளை அமைக்கவும்',lmp:'கடைசி மாதவிடாய் தேதி',update:'கண்காணிப்பை புதுப்பிக்கவும்',updated:'கர்ப்ப தேதிகள் வெற்றிகரமாக புதுப்பிக்கப்பட்டன.',development:'குழந்தையின் வளர்ச்சி',motherChanges:'தாயின் மாற்றங்கள்',clinicGuidance:'கிளினிக் வழிகாட்டல்',explore:'40 வாரங்களையும் பார்க்கவும்',size:'அளவு',disclaimer:'இது பொதுக் கல்வித் தகவல்களை வழங்குகிறது. தேதிகளையும் பராமரிப்புத் திட்டத்தையும் தகுதியான சுகாதார நிபுணருடன் உறுதிசெய்யவும்.'},
    appointments:{title:'கிளினிக் சந்திப்புகள்',readonly:'உங்கள் பாத்திரத்திற்கு சந்திப்புகள் பார்வை மட்டும். சேர்க்க, திருத்த அல்லது நீக்க தாய்க்கு மட்டுமே அனுமதி.',addTitle:'கிளினிக் சந்திப்பை சேர்க்கவும்',editTitle:'கிளினிக் சந்திப்பை திருத்தவும்',hospital:'மருத்துவமனை / கிளினிக்',hospitalPh:'உதா: நுகேகொட MOH அலுவலகம்',doctor:'மருத்துவர் / மருத்துவச்சி',type:'சந்திப்பு வகை',routine:'வழக்கமான கர்ப்ப கிளினிக்',scan:'அல்ட்ராசவுண்ட் ஸ்கேன்',blood:'இரத்த பரிசோதனை',vaccination:'தடுப்பூசி',specialist:'நிபுணர் ஆலோசனை',other:'மற்றவை',notesPh:'கிளினிக் புத்தகம், அறிக்கைகள், கேட்க வேண்டிய கேள்விகள்…',reminder:'செயலியில் நினைவூட்டலை இயக்கவும்',saveChanges:'மாற்றங்களை சேமிக்கவும்',addAppointment:'சந்திப்பை சேர்க்கவும்',next:'அடுத்த சந்திப்பு',reminderEnabled:'நினைவூட்டல் இயக்கப்பட்டுள்ளது.',myAppointments:'என் சந்திப்புகள்',empty:'இன்னும் சந்திப்புகள் சேர்க்கப்படவில்லை.',added:'சந்திப்பு சேர்க்கப்பட்டது.',updated:'சந்திப்பு புதுப்பிக்கப்பட்டது.',deleteConfirm:'இந்த சந்திப்பை நீக்கவா?'},
    health:{title:'டிஜிட்டல் சுகாதார பதிவுகள்',desc:'இரத்த அழுத்தம், எடை மற்றும் ஸ்கேன் அறிக்கைகளை பாதுகாப்பாக சேமிக்கவும்.',readonly:'உங்கள் பாத்திரத்திற்கு பதிவுகளை பார்க்கவும் கருத்து சேர்க்கவும் முடியும். உருவாக்க, திருத்த அல்லது நீக்க தாய்க்கு மட்டுமே அனுமதி.',addTitle:'சுகாதார பதிவை சேர்க்கவும்',editTitle:'சுகாதார பதிவை திருத்தவும்',recordType:'பதிவு வகை',weight:'எடை',bloodPressure:'இரத்த அழுத்தம்',scanReport:'ஸ்கேன் அறிக்கை',weightKg:'எடை (kg)',systolic:'சிஸ்டாலிக்',diastolic:'டயஸ்டாலிக்',pulse:'நாடித் துடிப்பு',reportTitle:'அறிக்கை தலைப்பு',scanType:'ஸ்கேன் வகை',file:'அறிக்கை கோப்பு',all:'அனைத்து பதிவுகள்',open:'அறிக்கையை திறக்கவும்',deleteConfirm:'இந்த சுகாதார பதிவை நிரந்தரமாக நீக்கவா?',openError:'ஸ்கேன் அறிக்கையை திறக்க முடியவில்லை'},
    emergency:{title:'ஒரு தொடு SOS',desc:'அவசர உதவி தேவைப்படும் போது மட்டும் பயன்படுத்தவும். உங்கள் தற்போதைய இருப்பிடம் சேமிக்கப்பட்ட தொடர்புகளுடன் பகிர தயாராகும்.',button:'அவசர SOS அனுப்பு',locating:'இருப்பிடம் கண்டறிகிறது…',needContact:'முதலில் தாய் குறைந்தது ஒரு அவசர தொடர்பை சேமிக்க வேண்டும்.',contacts:'சேமிக்கப்பட்ட அவசர தொடர்புகள்',name:'தொடர்பு பெயர்',relationship:'உறவு (துணைவர், சகோதரி…)',phone:'தொலைபேசி எண்',priority:'முன்னுரிமை',saveContact:'தொடர்பை சேமிக்கவும்',updateContact:'தொடர்பை புதுப்பிக்கவும்',sms:'SMS',call:'அழைக்க',openMaps:'வரைபடத்தில் இருப்பிடத்தை திறக்கவும்',history:'சமீபத்திய SOS செயல்கள்',notSupported:'இந்த உலாவி இருப்பிடத்தை ஆதரிக்கவில்லை.',denied:'இருப்பிட அனுமதி மறுக்கப்பட்டது.',failed:'உங்கள் இருப்பிடத்தை பெற முடியவில்லை.',requesting:'உங்கள் தற்போதைய இருப்பிடத்தை பெறுகிறது…'},
    finder:{title:'அருகிலுள்ள மருத்துவமனைகள், மருந்தகங்கள் மற்றும் குழந்தை கடைகள்',desc:'சாதன GPS ஐ பயன்படுத்தவும் அல்லது ஆயத்தொலைவுகளை உள்ளிடவும். உள்ளூர் மேம்பாட்டில் GPS பொதுவாக localhost அல்லது HTTPS இல் மட்டுமே இயங்கும்.',useLocation:'என் இருப்பிடத்தை பயன்படுத்து',colombo:'கொழும்பு மாதிரியை பயன்படுத்து',latitude:'அட்சரேகை, உதா: 6.9271',longitude:'தீர்க்கரேகை, உதா: 79.8612',searchHere:'இங்கே தேடவும்',all:'அனைத்து இடங்கள்',hospitals:'மருத்துவமனைகள்',pharmacies:'மருந்தகங்கள்',shops:'குழந்தை கடைகள்',within:'{km} கிமீக்குள்',centre:'தேடல் மையம்',openHospitals:'Google Maps இல் மருத்துவமனைகளை திறக்கவும்',openShops:'Google Maps இல் குழந்தை கடைகளை திறக்கவும்',results:'அருகிலுள்ள முடிவுகள்',filter:'பெயர் அல்லது பகுதி மூலம் வடிகட்டு',start:'தேடலை தொடங்க மேலே உங்கள் இருப்பிடத்தை தேர்ந்தெடுக்கவும்.',noResults:'இந்த தூரத்தில் வரைபட இடங்கள் இல்லை. பெரிய தூரம் அல்லது Google Maps ஐ முயற்சிக்கவும்.',directions:'வழித்தடம்',mapNote:'Google Places அமைக்கப்பட்டிருந்தால் அதன் இடத் தரவு பயன்படுத்தப்படும்; OpenStreetMap காப்புப்பிரதியாக பயன்படும். சேவைகளையும் திறந்திருக்கும் நேரத்தையும் முன்கூட்டியே உறுதிசெய்யவும்.',source:'தரவு மூலம்',selected:'தேர்ந்தெடுக்கப்பட்டது',openNow:'இப்போது திறந்துள்ளது',closedNow:'இப்போது மூடப்பட்டுள்ளது',addressUnavailable:'முகவரி கிடைக்கவில்லை',gpsHttps:'உலாவி இருப்பிடத்திற்கு HTTPS அல்லது localhost தேவை. கைமுறை இருப்பிடத்தை பயன்படுத்தவும்.',invalid:'செல்லுபடியாகும் அட்சரேகை மற்றும் தீர்க்கரேகையை உள்ளிடவும்.'},
    care:{signedIn:'உள்நுழைந்த வகை',linked:'இணைக்கப்பட்ட பராமரிப்பு குழு',invitation:'குடும்ப அழைப்புக் குறியீடு',inviteHelp:'இந்த குறியீட்டை நம்பகமான துணைவர் அல்லது சுகாதார நிபுணருடன் மட்டும் பகிரவும்.',permissions:'அனுமதி சுருக்கம்',area:'பகுதி',viewEdit:'பார்க்கவும் திருத்தவும்',viewOnly:'பார்வை மட்டும்',addEditDelete:'சேர்க்க, திருத்த மற்றும் நீக்க',careComments:'பராமரிப்பு குழு கருத்துகள்',pregnancyDates:'கர்ப்ப தேதிகள்',appointments:'சந்திப்புகள்',healthRecords:'சுகாதார பதிவுகள்',addComment:'கருத்து சேர்க்கவும்',commentAdded:'கருத்து வெற்றிகரமாக சேர்க்கப்பட்டது.'},
    wellbeing:{mood:'இன்று எப்படி உணர்கிறீர்கள்?',thanks:'பதிலளித்ததற்கு நன்றி. உங்கள் நல்வாழ்வு முக்கியம்!',forum:'சமூக மன்றம்',placeholder:'ஒரு கேள்வி அல்லது அனுபவத்தை பகிரவும்…',post:'பதிவிடு'},
    footer:'MomCare LK — CCS2313 சிறு திட்ட மாதிரி · குழு 05'
  }
};

Object.values(translations).forEach((x) => {
  Object.assign(x, {
    welcome: x.home.welcome, week: x.home.week, of40: x.home.of40, dueDate: x.home.dueDate,
    babyThisWeek: x.home.babyThisWeek, login: x.auth.login, register: x.auth.register,
    logout: x.auth.logout, email: x.auth.email, password: x.auth.password, fullName: x.auth.fullName,
    accountType: x.auth.accountType, noAccount: x.auth.noAccount, haveAccount: x.auth.haveAccount,
    loginWelcome: x.auth.loginWelcome, registerWelcome: x.auth.registerWelcome, demoAccounts: x.auth.demoAccounts,
    roleMom: x.roles.mom, rolePartner: x.roles.partner, roleDoctor: x.roles.doctor,
    moodTitle: x.wellbeing.mood, moodThanks: x.wellbeing.thanks, forum: x.wellbeing.forum,
    forumPlaceholder: x.wellbeing.placeholder, post: x.wellbeing.post,
    assistant: x.nav.health, assistantDesc: x.health.desc, ask: x.search, askPlaceholder: x.search,
    date: x.date, notes: x.notes, replies: x.comments,
    pillars: {
      health: x.health.title, healthDesc: x.health.desc,
      emergency: x.emergency.title, emergencyDesc: x.emergency.desc,
      shopping: x.finder.title, shoppingDesc: x.finder.desc,
      wellbeing: x.nav.wellbeing, wellbeingDesc: x.wellbeing.mood
    }
  });
});
